name: Build And Push Docker Image

on:
  workflow_call:
    inputs:
      component:
        required: true
        type: string

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: galam/${{ inputs.component }}
        
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./${{ inputs.component }
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Update repo description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: galam/${{ inputs.component }}
          readme-filepath: ./${{ inputs.component }}/Readme.md

        
